// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcWbgyBgzEvWhfUkc7AFCd46u2Rup2gk',
    appId: '1:529753332053:web:c06fcf62c07de4f47537dc',
    messagingSenderId: '529753332053',
    projectId: 'postgrade-b487e',
    authDomain: 'postgrade-b487e.firebaseapp.com',
    databaseURL: 'https://postgrade-b487e-default-rtdb.firebaseio.com',
    storageBucket: 'postgrade-b487e.appspot.com',
    measurementId: 'G-YP996V565P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIr11VVmgBOArMRSxj3W5RNJ0gKMgdVvU',
    appId: '1:529753332053:android:8f9c2de5388ec4537537dc',
    messagingSenderId: '529753332053',
    projectId: 'postgrade-b487e',
    databaseURL: 'https://postgrade-b487e-default-rtdb.firebaseio.com',
    storageBucket: 'postgrade-b487e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_z53g-ZSNjzV1O8E3rnf-1A3GA_ky34',
    appId: '1:529753332053:ios:1d7a60e41bdc16ea7537dc',
    messagingSenderId: '529753332053',
    projectId: 'postgrade-b487e',
    databaseURL: 'https://postgrade-b487e-default-rtdb.firebaseio.com',
    storageBucket: 'postgrade-b487e.appspot.com',
    iosBundleId: 'com.example.postgrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_z53g-ZSNjzV1O8E3rnf-1A3GA_ky34',
    appId: '1:529753332053:ios:1d7a60e41bdc16ea7537dc',
    messagingSenderId: '529753332053',
    projectId: 'postgrade-b487e',
    databaseURL: 'https://postgrade-b487e-default-rtdb.firebaseio.com',
    storageBucket: 'postgrade-b487e.appspot.com',
    iosBundleId: 'com.example.postgrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkcWbgyBgzEvWhfUkc7AFCd46u2Rup2gk',
    appId: '1:529753332053:web:1c4457bbf3355ef97537dc',
    messagingSenderId: '529753332053',
    projectId: 'postgrade-b487e',
    authDomain: 'postgrade-b487e.firebaseapp.com',
    databaseURL: 'https://postgrade-b487e-default-rtdb.firebaseio.com',
    storageBucket: 'postgrade-b487e.appspot.com',
    measurementId: 'G-HD5RQ6C1JF',
  );
}
